---
- hosts: localhost
  become: no

  tasks:

  - name: Enable memory leak in the business backend
    uri:
      url: "http://localhost:8091/services/ConfigurationService/setPluginEnabled?name=MediumMemoryLeak&enabled=true"
      method: GET
      status_code: [200, 201, 202]
      validate_certs: no
    delegate_to: easyTravel