---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
  name: easytravel-web
spec:
  rules:
  - host: {{ .Values.ingress.domain }}
    http:
      paths:
      - backend:
          service:
            name: nginx-custom-web
            port:
              name: nginx
        path: /
        pathType: ImplementationSpecific
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
  name: easytravel-launcher
spec:
  rules:
  - host: {{ .Values.ingress.launcher_domain }}
    http:
      paths:
      - backend:
          service:
            name: nginx-custom-launcher
            port:
              name: nginx
        path: /
        pathType: ImplementationSpecific