---
kind: Service
apiVersion: v1
metadata:
  name: nginx-custom-web
spec:
  selector:
    app: nginx-web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: nginx
---
kind: Service
apiVersion: v1
metadata:
  name: nginx-custom-launcher
spec:
  selector:
    app: nginx-launcher
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: nginx